services:
  clickhouse:
    container_name: clickhouse
    image: "clickhouse/clickhouse-server"
    expose:
      - "8123"
      - "9000"
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=metricflow
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
